/**
 * The site's mark is not a logo file — it's a seedicon, generated by the
 * package this site documents, from the author's wallet address. Keeping the
 * seed here (rather than in a component) lets the navbar, the footer and the
 * pre-rendered favicon all agree on it without importing each other.
 */
export const BRAND_SEED = "0xba32a6076cd558947b3da6148fc4994b421eed56";
