"use client";

import { useId, useRef, useState, type KeyboardEvent } from "react";
import { generateAvatar, generateAvatarDataUri, SEEDICON_STYLES } from "seedicon";

import { CODE_PRE } from "../lib/ui";
import { highlight } from "../lib/highlight";

/**
 * The Usage section: one tab per entry point, each showing the import, the
 * call, what the call returns, and the avatar that comes out of it.
 *
 * The old version of this section was a single continuous <pre> where the four
 * entry points were separated only by `//` comments, which meant that someone
 * arriving with one question ("how do I use this in React?") had to read all
 * four answers to find theirs.
 *
 * Like the playground, the previews are the published package running in the
 * browser rather than pictures of it — if a tab renders, that entry point works.
 */

/** The playground's default seed, reused so the two sections agree. */
const DEMO_SEED = "550e8400-e29b-41d4-a716-446655440000";
const PREVIEW_SIZE = 44;

type Entry = {
  /** Label on the tab: the thing you import. */
  tab: string;
  /** Where you would be when you reach for it. */
  when: string;
  returns: string;
  returnNote: string;
  code: string;
  /** SVG markup for the preview column, generated by the package itself. */
  preview: string;
  caption: string;
  /** Shown above the preview when the return value is worth seeing as text. */
  uri?: string;
};

const dataUri = generateAvatarDataUri({ seed: DEMO_SEED, size: PREVIEW_SIZE });

const ENTRIES: Entry[] = [
  {
    tab: "generateAvatar",
    when: "Anywhere",
    returns: "string",
    returnNote: "raw <svg> markup",
    code: `import { generateAvatar } from "seedicon";

const svg = generateAvatar({
  seed: user.id,
  style: "truchet",
});`,
    preview: generateAvatar({
      seed: DEMO_SEED,
      style: "truchet",
      size: PREVIEW_SIZE,
      shape: "rounded",
    }),
    caption: "runs during SSR: no canvas, no window",
  },
  {
    tab: "generateAvatarDataUri",
    when: "In <img> or CSS",
    returns: "string",
    returnNote: "the same SVG, URL-encoded",
    code: `import { generateAvatarDataUri } from "seedicon";

const src = generateAvatarDataUri({ seed: user.id });`,
    preview: generateAvatar({
      seed: DEMO_SEED,
      size: PREVIEW_SIZE,
      shape: "rounded",
    }),
    // The real value, cut at the point where it stops being informative.
    uri: `${dataUri.slice(0, 42)}…`,
    caption: "drops straight into <img src>",
  },
  {
    tab: "<Avatar />",
    when: "In React",
    returns: "JSX.Element",
    returnNote: "the only entry point that imports React",
    code: `import { Avatar } from "seedicon/react";

<Avatar seed={user.id} size={40} shape="circle" />`,
    preview: generateAvatar({
      seed: DEMO_SEED,
      size: PREVIEW_SIZE,
      shape: "circle",
    }),
    caption: 'shape="circle"',
  },
  {
    tab: "seedicon/pixelart",
    when: "One style alone",
    returns: "string",
    returnNote: "pulls in nothing else",
    code: `import { pixelart } from "seedicon/pixelart";

const svg = pixelart({ seed: user.id, size: 40, shape: "circle" });`,
    preview: generateAvatar({
      seed: DEMO_SEED,
      style: "pixelart",
      size: PREVIEW_SIZE,
      shape: "circle",
    }),
    caption: `${SEEDICON_STYLES.length} styles, one entry point each`,
  },
];

const TAB =
  "cursor-pointer rounded-t-lg border-b-2 border-transparent px-3.5 py-2.5 font-mono text-xs text-faint transition-colors hover:text-dim focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-primary aria-selected:border-primary aria-selected:bg-input aria-selected:text-foreground";

export function UsageTabs() {
  const [active, setActive] = useState(0);
  const [copied, setCopied] = useState(false);
  const tabs = useRef<(HTMLButtonElement | null)[]>([]);
  const id = useId();

  const entry = ENTRIES[active];

  function select(next: number) {
    setActive(next);
    setCopied(false);
  }

  /** Arrow keys move between tabs, which is what a tablist is expected to do
   *  — the buttons carry a roving tabindex so Tab itself skips past the group. */
  function onKeyDown(event: KeyboardEvent<HTMLButtonElement>) {
    const last = ENTRIES.length - 1;
    let next: number | null = null;

    if (event.key === "ArrowRight") next = active === last ? 0 : active + 1;
    else if (event.key === "ArrowLeft") next = active === 0 ? last : active - 1;
    else if (event.key === "Home") next = 0;
    else if (event.key === "End") next = last;

    if (next === null) return;
    event.preventDefault();
    select(next);
    tabs.current[next]?.focus();
  }

  async function copy() {
    try {
      await navigator.clipboard.writeText(entry.code);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1400);
    } catch {
      // Clipboard access can be denied (insecure context, permissions).
      // Ignoring it is fine — the snippet is visible and selectable.
    }
  }

  return (
    <div className="overflow-hidden rounded-xl border border-border bg-raised">
      <div
        role="tablist"
        aria-label="Ways to use seedicon"
        className="flex flex-wrap gap-0.5 px-1.5 pt-1.5"
      >
        {ENTRIES.map((option, index) => (
          <button
            key={option.tab}
            ref={(node) => {
              tabs.current[index] = node;
            }}
            type="button"
            role="tab"
            id={`${id}-tab-${index}`}
            aria-selected={index === active}
            aria-controls={`${id}-panel`}
            tabIndex={index === active ? 0 : -1}
            onClick={() => select(index)}
            onKeyDown={onKeyDown}
            className={TAB}
          >
            {option.tab}
          </button>
        ))}
      </div>

      <div
        role="tabpanel"
        id={`${id}-panel`}
        aria-labelledby={`${id}-tab-${active}`}
        className="grid grid-cols-1 bg-input min-[760px]:grid-cols-[minmax(0,1fr)_210px]"
      >
        <div className="relative min-w-0 px-[18px] pb-5 pt-[18px]">
          <button
            type="button"
            onClick={copy}
            className="absolute right-2.5 top-2.5 cursor-pointer rounded-md border border-border-strong bg-raised px-2.5 py-[5px] font-mono text-[11px] text-dim transition-colors hover:border-primary hover:text-foreground"
          >
            {copied ? "copied" : "copy"}
          </button>

          <p className="mb-3 border-b border-dashed border-border pb-3 pr-16 font-mono text-[11px] text-faint">
            {entry.when} · returns{" "}
            <b className="font-medium text-dim">{entry.returns}</b> —{" "}
            {entry.returnNote}
          </p>

          <pre className={`${CODE_PRE} overflow-x-auto`}>
            {highlight(entry.code)}
          </pre>
        </div>

        {/* The preview column. The markup is injected, but the seed never
            reaches it as markup: it goes through seedicon's hash and comes
            back out as numbers, so there is nothing here to escape. */}
        <figure className="flex flex-row items-center justify-center gap-4 border-t border-border p-[18px] text-center min-[760px]:flex-col min-[760px]:gap-3 min-[760px]:border-l min-[760px]:border-t-0">
          {entry.uri ? (
            <code className="w-full break-all rounded-md border border-border bg-background px-[7px] py-1.5 text-left font-mono text-[10px] leading-normal text-mint">
              {entry.uri}
            </code>
          ) : null}
          <span dangerouslySetInnerHTML={{ __html: entry.preview }} />
          <figcaption className="font-mono text-[10.5px] leading-normal text-faint">
            {entry.caption}
          </figcaption>
        </figure>
      </div>
    </div>
  );
}
