import { useMemo } from "react";
import { generateAvatar, type SeediconOptions } from "./index.js";

export interface AvatarProps extends Omit<SeediconOptions, "size"> {
  size?: number;
  /** Passed through to the wrapping <div>. */
  className?: string;
}

/**
 * React wrapper around {@link generateAvatar}. Unlike canvas-based
 * generators (e.g. `@download/blockies`), this renders synchronously to
 * SVG markup — no `useEffect` + DOM ref dance, no flash of empty avatar,
 * and it works during server-side rendering (Next.js, Remix, etc) since
 * there's no canvas or `window` involved.
 *
 * ```tsx
 * <Avatar seed={address} style="pixels" size={40} shape="circle" />
 * ```
 *
 * Need more control over the wrapper (custom CSS, data attributes)? Call
 * {@link generateAvatar} directly and render the markup yourself — this
 * component is a thin convenience, not the only way to use seedicon.
 */
export function Avatar({
  seed,
  style,
  size = 40,
  shape,
  radius,
  className,
}: AvatarProps) {
  const svg = useMemo(
    () => generateAvatar({ seed, style, size, shape, radius }),
    [seed, style, size, shape, radius],
  );

  return (
    <div
      className={className}
      style={{ width: size, height: size, lineHeight: 0 }}
      // eslint-disable-next-line react/no-danger -- svg is generated by us, not user input
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
